# Generated by Django 2.2 on 2019-08-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='dataLancamento',
            field=models.DateField(verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dataLancamento',
            field=models.DateField(verbose_name='Data de Lançamento'),
        ),
    ]
