# Generated by Django 2.1.7 on 2019-11-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
