# Generated by Django 2.2 on 2019-08-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('resumo', models.CharField(max_length=100)),
                ('conteudo', models.TextField(verbose_name='Descrição')),
                ('autor', models.CharField(max_length=20)),
                ('dataPublicacao', models.DateField(auto_now=True, verbose_name='Data de publicação')),
            ],
        ),
    ]
